interface Alternative {
  fertilizer: string;
  probability: number;
}

interface Props {
  alternatives: Alternative[];
}

export default function AlternativePredictions({
  alternatives,
}: Props) {
  return (
    <div className="alternatives-card">

      <h2>
        📊 Top 3 Fertilizer Recommendations
      </h2>

      <p className="section-description">
        These are the top 3 fertilizer recommendations
        generated by our model.
      </p>

      <div className="alternatives-list">

        {alternatives.map((item, index) => (

          <div
            key={index}
            className="alternative-item"
          >

            <div className="alternative-rank">
              #{index + 1}
            </div>

            <div className="alternative-info">

              <h3>
                {item.fertilizer}
              </h3>

              <div className="probability-bar">
                <div
                  className="probability-fill"
                  style={{
                    width: `${item.probability}%`,
                  }}
                />

              </div>

            </div>

            <div className="probability-value">
              {item.probability}%
            </div>

          </div>

        ))}

      </div>
   </div>
  );
}